ERROR[db.py:__init__:23]:{db_Connect_Error: {"reason":1045 (28000): Access denied for user 'shivam'@'localhost' (using password: YES)}}
ERROR[db.py:query:82]:{"db_query_failed":select userName, password, attempts, lastAttempt, reset from users where userName = 'shivam', "error":Invalid format specifier}
ERROR[login.py:getUsers:313]:{"login_getUser_Failed":{"userName":shivam}}
ERROR[login.py:matchPassword:285]:{"login_matchPassword_Failed":{"userName":shivam}}
ERROR[db.py:__init__:23]:{db_Connect_Error: {"reason":1045 (28000): Access denied for user 'shivam'@'localhost' (using password: YES)}}
ERROR[db.py:query:82]:{"db_query_failed":select userName, password, attempts, lastAttempt, reset from users where userName = 'shivam', "error":Invalid format specifier}
ERROR[login.py:getUsers:315]:{"login_getUser_Failed":{"userName":shivam}}
ERROR[login.py:matchPassword:287]:{"login_matchPassword_funcFailed":{"userName":shivam}}
ERROR[db.py:__init__:23]:{db_Connect_Error: {"reason":1045 (28000): Access denied for user 'shivam'@'localhost' (using password: YES)}}
ERROR[db.py:query:82]:{"db_query_failed":select userName, password, attempts, lastAttempt, reset from users where userName = 'shivam', "error":Invalid format specifier}
ERROR[login.py:getUsers:315]:{"login_getUser_Failed":{"userName":shivam}}
ERROR[login.py:matchPassword:287]:{"login_matchPassword_funcFailed":{"userName":shivam}}
INFO[login.py:getUsers:309]:{"login_getUser_Successful":{"userName":shivam}}
ERROR[login.py:matchPassword:244]:{"login_matchPassword_passwordFailed":{"userName":shivam}}
INFO[login.py:getUsers:309]:{"login_getUser_Successful":{"userName":shivam}}
ERROR[login.py:matchPassword:238]:{"login_matchPassword_Successful":{"userName":shivam}}
