ERROR[db.py:__query__:132]:queryError -> 1054 (42S22): Unknown column 'prescriptionPath' in 'field list'
ERROR[custQueries.py:create:255]:{"custQueries_Create_Error":{custName:shivam, custEmail:shivamswims456@gmail.com, phoneNumber:9693432136, particularName:K.F.T_1, particularId:1, particularSec:1, payment:C.O.D, status:INTIALIZED, reportLink:}}
INFO[custQueries.py:create:251]:{"custQueries_Create_Error":{custName:shivam, custEmail:shivamswims456@gmail.com, phoneNumber:9693432136, particularName:K.F.T_1, particularId:1, particularSec:1, payment:C.O.D, status:INTIALIZED, reportLink:}}
